spring:
    datasource:    
        password: password
        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=shopdb
        username: postgres
    http:
        multipart:
            max-file-size: 10000000KB
            max-request-size: 10000000KB
    jackson:
        serialization:
            write-dates-as-timestamps: false

server:
    contextPath: /htwotest
    port: 7007
    servlet-path: /*
      
---

spring:
    profiles: test
    datasource:    
        password: sa
        url: "jdbc:h2:mem:db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        username: sa


